name: Autotesting

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: npm install
                
      - name: Run Tests
        run: npm test