name: Autotesting

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: windows-latest
    
    steps:
      - name: Tests code
        uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
                
      - name: Run Tests
        run: npm test